### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by mezgoodle** [mezidia/bd-project#1]
Write your **ideas** here:

> Also then we rename this repository

**Comment by VsIG-official** [comment]
Booking by @La7rodectus

**Comment by mezgoodle** [comment]
Also then we rename this repository

**Comment by mezgoodle** [comment]
- Library Data Management
- Solution for Saving Student Records
- Railway System

[Link ](https://www.upgrad.com/blog/dbms-project-ideas-for-beginners/) to the site

**Comment by VsIG-official** [comment]
>     * Solution for Saving Student Records
We can make Our own Campus

**Comment by VsIG-official** [comment]
>     * Railway System
Sounds interesting to Me

**Comment by Dmytrenko-Roman** [comment]
CIA database.

**Comment by fhrr-sht** [comment]
telegram bot which helps us with timetable, Zoom links, homework, youtube videos, etc 
(maybe it's what VsIG-official called Our own Campus)

**Comment by mezgoodle** [comment]
> Booking by @La7rodectus

There is [Booking.com API](https://developers.booking.com/api/index.html)

**Comment by VsIG-official** [comment]
DB-project
